#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Nagominashare.Resource", IsApplication=true)]

namespace Nagominashare
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dajare_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dajaring_label = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int generate_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monitor_toggle_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int share_button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int standby_label = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int twitter_share_button = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int container = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int dajare_jpn = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int dajare_romaji = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int dajaring_label = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int generate_button = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int monitor_toggle_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int share_button = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int standby_label = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dajare = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainActivity = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int NAIST_Japanese_Dictionary_HackU = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
